### ISSUE TITLE
Check if existing "a-b" cut parallel text what does not have "a-b" cut in leading text.

### ISSUE THREAD

**Issue by anwolosz** [anwolosz/synopsis#101]

**Comment by anwolosz** [comment]
All parallel text citations which have a-b cut.

Pairs:
**33.  mk 6.1-6a** + **98. mk 6.6b**
**50.  lk 6.17-20a** + **51. lk 6.20b-23**

Only "a":
43.  jn 5.8-9a = 92.  jn 5.8-9a 
50.  mk 3.7-13a = 77.  mk 3.7-13a
289. mt 10.17-22a
**340. mt 27.28-31a**
340. mk 15.17-20a

Only "b":
123. lk 8.18b
291. lk 17.37b
348. jn 19,24b-27

Bold texts show if it has been already cut in leading texts.
7 new cut needed, which is manageable. Also good idea, because it keeps closer this way to Synopsis Quattuor Evangeliorum.

I'm moving on with doing these cuts in each translation.

Also note, that [Notes-on-sources](https://github.com/anwolosz/synopsis/wiki/Notes-on-sources) are updated.

**Comment by jano-wol** [comment]
That is a great news!
Please let me merge one more translation with the old structure, as it is completely ready now:
https://github.com/anwolosz/synopsis/pull/100

I will inform RW that no new translations can be added until we adapt to the new structure.
Let us know if we can help with the cuts (reviewing etc.)
