### ISSUE TITLE
Wiki change: Notes -> Differences from the sources. KNB jn19,24

### ISSUE THREAD

**Issue by jano-wol** [anwolosz/synopsis#109]
The API response 
https://szentiras.hu/api/ref/Jn%2019,24/KNB
and
https://katolikus.hu/szentiras/KNB/Jn/19

are aligned, but a mess. I proposed a fix for it in:
https://github.com/anwolosz/synopsis/pull/108

**Comment by anwolosz** [comment]
This problem was noticed, and only not solved because I worked on a-b cuts.
https://github.com/users/anwolosz/projects/1?pane=issue&itemId=86651578

The decision is not critical, it's an szentiras.hu API bug. I checked the book. "A katonát tehát ezt tették" is tha last sentence of the verse.
