### ISSUE TITLE
Arrows are not working when the url is: https://www.synopticus.org/

### ISSUE THREAD

**Issue by jano-wol** [anwolosz/synopsis#11]
When the url is 
https://www.synopticus.org/
the "Következő törzsszöveg" arrows are not working.

On the other hand, when the url contains the Bible translation e.g:
https://www.synopticus.org/hu/SZIT/
the arrows are working fine.

**Comment by anwolosz** [comment]
Thank you!
Resolved by redirecting from "/" to "/hu/SZIT"
