### ISSUE TITLE
Restructure wiki pages

### ISSUE THREAD

**Issue by anwolosz** [anwolosz/synopsis#116]
I propose the following structure:
```

- Home
- - Differences from the sources
- - - Szent István Társulati Biblia
- - - Káldi Neovulgáta
- - - Biblia Jakuba Wujka
- - - ...
- - - Synopsis Quattuor Evangeliorum
- - Notes on sources
- - - Findings
- - - Legen
- - Errata
```

**Comment by anwolosz** [comment]
@jano-wol 
What do you mean by:
- - - Szent István Társulati Biblia
- - - Káldi Neovulgáta
- - - Biblia Jakuba Wujka

Should I list every translation even if there is no related change?
Right now that page is just a list of differences. I thought about some smart grouping, but nothing extremely good came to my mind.

**Comment by jano-wol** [comment]
No-no, I think we should create translation entry, only if there is at least one difference to mention.

**Comment by anwolosz** [comment]
Done: https://github.com/anwolosz/synopsis/wiki
