### ISSUE TITLE
Investigate using character encoding on windows and linux

### ISSUE THREAD

**Issue by anwolosz** [anwolosz/synopsis#29]
Running this script on windows (powershell)
`python3 tests/json_test.py src/assets/translations .\tests\synopsis_blank.json update`
outputs the following error:
`Invalid json= src/assets/translations\bt.json. error='charmap' codec can't decode byte 0x81 in position 94: character maps to <undefined>`
This change solves the problem:
`with open(file_to_check) as f:`
=>
`with open(file_to_check, encoding='utf-8') as f:`

Please do further investigation, if this change does not ruin the tests on linux.

**Comment by jano-wol** [comment]
ChatGPT's point on the problem:
with open(file_to_check) as f 
"Relies on the system's default encoding to open the file. In most cases, especially on modern Unix-like systems (such as Linux or macOS), this could default to 'UTF-8'. However, on Windows, the default encoding could be different, such as 'cp1252'."

Later it also mentions:
"In general, it’s recommended to explicitly specify the encoding when working with text files..."

This thread also mentions this Windows behaviour:
https://stackoverflow.com/questions/36303919/what-encoding-does-open-use-by-default

Fixing PR:
https://github.com/anwolosz/synopsis/pull/30

**Comment by jano-wol** [comment]
Fixing PR merged.
