### ISSUE TITLE
ESV 242

### ISSUE THREAD

**Issue by jano-wol** [anwolosz/synopsis#33]
https://www.synopticus.org/hu/ESV/242

Please check the text, it mentions:
[The earliest manuscripts do not include 7:53–8:11.]

This is aligned with:
https://www.biblegateway.com/passage/?search=John%207&version=ESV

Still, I think we should delete the comment and the "[[" and "]]" brackets.

**Comment by anwolosz** [comment]
Thank you!
Same issue occures in section 353 and 363.
