### ISSUE TITLE
Unexpected (vertical) offset

### ISSUE THREAD

**Issue by jano-wol** [anwolosz/synopsis#34]
Arrows are working generally very nicely, however sometimes I see an unexpected (vertical) offset.
Check e. g.:
http://localhost:5173/hu/KG#250
or
http://localhost:5173/hu/KG#156

I think the problem might be related to the fact that these sections are one above a new  part (e.g section 250 is followed by part "XII. Jézus működése Júdeában"), although I am not sure as I do not see this problem with:
http://localhost:5173/hu/KG#83

**Comment by anwolosz** [comment]
I suspect the problem occurs when the section box is fit inside the browsers view port. For example for me section 76, 250 and 286 are has unwanted offset (in KG), but if i resize the browser window both of them works well.

Important that for me it only occurs if I visit a section using # link, or use the function buttons, but not when I use the navigation buttons.
By function buttons I mean:
![image](https://github.com/user-attachments/assets/43b5f48e-4b9f-43c9-8456-0b462f56cada)
![image](https://github.com/user-attachments/assets/b68b7a6c-0d2c-41f9-b4b5-d5ebd1c55673)
By navigation buttons I mean:
![image](https://github.com/user-attachments/assets/6b91b580-cab2-484f-9722-c44c6103c18e)
![image](https://github.com/user-attachments/assets/8289f753-3855-42e9-be94-02cc09992284)

(Let me know if you have better idea for naming 😃 )

Just for clarification: do you notice the same behavior as I do with the same tools?

**Comment by jano-wol** [comment]
Yes, the same behavior here, navigation buttons are OK, unexpected offset occurs only when function buttons or # links are used. (# link behavior is quite interesting, as for the first time when I write the link to the browser, unexpected offset occurs, but then, if I highlight the link in the browser and hit enter, than second time the section box is correctly positioned.)

**Comment by anwolosz** [comment]
@jano-wol FYI

When the page is loading the synopsis parts are rendered one by one. This feature is necessary so when the page is visited the user don't have to wait until the whole page is rendered. (Except if he/she visits a section from the last part.)

When you visit a # link, or use function buttons, the same thing happens. It ASAP scrolls to the anchor point. If the section box is small at that moment the section bottom is the bottom of the page. When the next part is rendered the scrolling is not corrected.

**Comment by anwolosz** [comment]
Fix in : https://github.com/anwolosz/synopsis/commit/7c83ee186929f97ebee66043271637f3f95b0d51
Please close this issue if you agree with it.

Visiting `#1` is not working properly, but that's another issue. See it here: #35

**Comment by jano-wol** [comment]
Fixing commit resolved the issue. 
Thx for the info on the root cause of the problem!
