### ISSUE TITLE
Matthew 18,11

### ISSUE THREAD

**Issue by jano-wol** [anwolosz/synopsis#40]
Matthew 18,11 is deleted in some manuscripts.
As it defined to be parallel to Luke 19,1-10 (in fact it seems to me that Matthew 18,11 == Luke 19,10)  weird things are happening in section 265.

KG and SZIT look normal.

KNB and ESV are empty:
https://www.synopticus.org/hu/KNB/265
https://www.synopticus.org/hu/ESV/265

UF and BT are using brackets to signalize the issue:
https://www.synopticus.org/hu/UF/265
https://www.synopticus.org/hu/BT/265 

I am not sure how to handle this divergence.

**Comment by jano-wol** [comment]
Also before making any decision it might worth to examine:
https://en.wikipedia.org/wiki/List_of_New_Testament_verses_not_included_in_modern_English_translations

**Comment by anwolosz** [comment]
Thank you, I do know about it. As far as I'm concerned even if the verses missing in the main text, most publisher mention the details in the footnotes. I believe the best If we keep it as the publishers decided about it. (I don't want to open pandora's box :D ) 

It might be a good idea to remove "empty"  citations boxes, but I also don't mind to emphasize if other translation contains it.

I close it for now, but feel free to share your ideas and open it again if needed.
