### ISSUE TITLE
VULG verses are not aligned with other manuscripts

### ISSUE THREAD

**Issue by jano-wol** [anwolosz/synopsis#45]
Please check:
http://localhost:5173/en/VULG/164
http://localhost:5173/en/VULG/165

The conversation on the "didrachma" is clearly in 164, meaning that Matthew 17,23 in VULG is not aligned with the other translations. I just randomly checked this part of the Gospel, indicating that there can be several such misalignments.

**Comment by jano-wol** [comment]
Maybe we are experiencing the effect that the disclaimer is talking about:
https://github.com/aseemsavio/Biblia-Sacra-Vulgata

**Comment by anwolosz** [comment]
Thank you!
I will parse Nova Vulgata then:
https://www.vatican.va/archive/bible/nova_vulgata/documents/nova-vulgata_nt_evang-matthaeum_lt.html#17

**Comment by jano-wol** [comment]
Sacra Vulgata integration difficulties were noted -> Changing the latin muniscript to Nova Vulgata is in progress.
