### ISSUE TITLE
Go back one page handling could be improved

### ISSUE THREAD

**Issue by jano-wol** [anwolosz/synopsis#46]
Start from
http://localhost:5173/hu/KG#172

Click on the function button of section **173**.
Push "Go back one page" on the browser toolbar. I would expect to go back to section 173, but currently we are going back to 172.

**Comment by anwolosz** [comment]
Done: https://github.com/anwolosz/synopsis/commit/a646aac25234a3465f34d2c8c4a7333cbdcdfb00
