### ISSUE TITLE
Navigation button makes text box stucked in the corner

### ISSUE THREAD

**Issue by jano-wol** [anwolosz/synopsis#5]
Repro: 
click on a navigation button on a subsection page (e.g. on https://www.anwolosz.hu/1).

![image](https://github.com/anwolosz/synopsis/assets/78079945/8837e466-2b9e-43ed-b785-411fc070caf2)

**Comment by anwolosz** [comment]
Recent commit hide navigation buttons on subsection pages. This way the issue is resolved.
