### ISSUE TITLE
Manual testing in some other browsers

### ISSUE THREAD

**Issue by anwolosz** [anwolosz/synopsis#51]
Please click around in various popular browsers:

- Firefox
- Chrome
- Edge

**Comment by jano-wol** [comment]
KNB review was done with Chrome (Windows OS). Everything was fine.

**Comment by jano-wol** [comment]
RUF review 1-200 was done in Edge (Windows OS). Everything was fine.

**Comment by jano-wol** [comment]
RUF 201-367 and final review was done on Fireforx (Windows OS).
Everything worked fine, browser depenent issues were not identified.
