### ISSUE TITLE
Unexpected switch to default translation

### ISSUE THREAD

**Issue by jano-wol** [anwolosz/synopsis#62]
On the main branch try out link:
http://localhost:5173/hu/SZIT#35

The loaded page is unexpectedly automatically changing to:
http://localhost:5173/hu/KG#35

As I see the error was introduced by revision:
17b4b1d367d2e684fa3ed6a1fe7ca5802cc836fd

(At least I do not see the error in the preceding revision: 72e20ddf06ecb91db843a2fb835ada89c871663e.)

**Comment by anwolosz** [comment]
Fixed in: https://github.com/anwolosz/synopsis/commit/374c990d26c22c4a0b7bceaf8f31dead53dac0ff
I close it for now, but please manual test it @jano-wol

**Comment by jano-wol** [comment]
OK!
