### ISSUE TITLE
Consider to delete sections 358, 359 and 360

### ISSUE THREAD

**Issue by jano-wol** [anwolosz/synopsis#67]
They have no main bodies; sections 359 and 364 are identical except for their titles.

**Comment by anwolosz** [comment]
What about 358? It also has no main text.

**Comment by jano-wol** [comment]
True! I think we could delete that one also.

**Comment by anwolosz** [comment]
Deleted in: https://github.com/anwolosz/synopsis/commit/1e30458af5beba23b7cd0c5ebaf188a4dadb15e1
