### ISSUE TITLE
Review toLeading.json

### ISSUE THREAD

**Issue by jano-wol** [anwolosz/synopsis#69]
Check that the redirecting links are pointing to the best possible main body.

**Comment by anwolosz** [comment]
Sadly Szinopszis is not available in any source I know. I'll try a library someday.

**Comment by jano-wol** [comment]
I wrote a test to find intersections between a parallel text and body texts. Based on this, only the leading positions of the following 16 parallel texts are ambiguous (in all other cases, a body text completely covers the parallel text):

mt1,1-17 {1, 6}
mk6,1-6 {139, 142}
lk6,17-20 {77, 78}
lk6,20-23 {77, 78}
mk3,7-13 {48, 49}
mt5,38-48 {58, 59}
mt7,21-27 {74, 75}
mk6,6 {139, 142}
lk10,12-15 {177, 178}
lk17,3 {229, 230}
mt24,42-51 {296, 297}
mk13,19-23 {290, 291}
jn2,13-17 {24, 25}
mt25,13-15 {298, 299}
mt27,28-31 {342, 343}
mk15,17-20 {342, 343}

**Comment by anwolosz** [comment]
@jano-wol 
I found out that in Synopsis Quattour Evangeliorum this info might be presented.
Eg. check section 282. Under it you can see (cf. nr. 182) which is really a relevant reference. I don't know what is "cf. nr." but if you can find out something please let me know!

**Comment by jano-wol** [comment]
Interesting, this can help us out!

On cf. : https://hu.wikipedia.org/wiki/V%C3%B6.
And nr. is the section id.

**Comment by jano-wol** [comment]
We checked all the listed possibilities. PR merged:
https://github.com/anwolosz/synopsis/pull/155
