### ISSUE TITLE
Bible text error in KNB Mt 5,43

### ISSUE THREAD

**Issue by jano-wol** [anwolosz/synopsis#76]
Verse contains typo: "felebarátodatés".

https://www.synopticus.org/hu/KNB/59
https://szentiras.hu/api/idezet/Mt5,43/KNB

Somewhat similar to:
https://github.com/anwolosz/synopsis/issues/73

**Comment by jano-wol** [comment]
I found some similar typos in KNB Jn 12,40: "szemüketés", "szemükkelés".
https://www.synopticus.org/hu/KNB/303
https://szentiras.hu/api/idezet/Jn12,40/KNB

**Comment by anwolosz** [comment]
Done in: 19f6d881b3e205c85258a6781d40f82afc42de3a
